### ISSUE TITLE
download zipfile instead?

### ISSUE THREAD

**Issue by wikfeldt** [ENCCS/supercomputing4ai#5]
password authentication isn't supported any longer, so it won't work to do:

https://github.com/ENCCS/supercomputing4ai/blob/22272b8e94450523a50226d2ebee16ff942993b5/content/folders_and_transfer.rst?plain=1#L53

right? And most users will not have set up ssh key on Dardel for GitHub, so don't we have to change this to download of zipfile with wget? But for some reason even that's not working for me:

``` 
$ wget https://github.com/ENCCS/supercomputing4ai_demo/archive/refs/heads/master.zip

...
HTTP request sent, awaiting response... 404 Not Found
2024-09-20 13:55:10 ERROR 404: Not Found.
```

hmm

**Comment by wikfeldt** [comment]
`curl -L -O https://github.com/ENCCS/supercomputing4ai_demo/archive/refs/heads/master.zip`
~~works however! what am i missing about wget?~~

edit: duh, no `curl -L -O` just creates an empty master.zip file...

**Comment by ffrancesco94** [comment]
> password authentication isn't supported any longer, so it won't work to do:
> 
> https://github.com/ENCCS/supercomputing4ai/blob/22272b8e94450523a50226d2ebee16ff942993b5/content/folders_and_transfer.rst?plain=1#L53
> 
> right? And most users will not have set up ssh key on Dardel for GitHub, so don't we have to change this to download of zipfile with wget? But for some reason even that's not working for me:
> 
> ```
> $ wget https://github.com/ENCCS/supercomputing4ai_demo/archive/refs/heads/master.zip
> 
> ...
> HTTP request sent, awaiting response... 404 Not Found
> 2024-09-20 13:55:10 ERROR 404: Not Found.
> ```
> 
> hmm

Right now the repo is private, so only us in the organisation can see it. But for participants to download it I have to make it public, so they won't need the password for that, right?

**Comment by wikfeldt** [comment]
lol, problem was simply that repo was closed. Closing issue
