### ISSUE TITLE
wrong module name?

### ISSUE THREAD

**Issue by wikfeldt** [ENCCS/supercomputing4ai#8]
https://github.com/ENCCS/supercomputing4ai/blob/fe27a5ddab51b222483fd6dd8386b86f2232d2cb/content/software_modules.rst?plain=1#L38

i get:
```
> ml ImageMagick
Lmod has detected the following error:  The following module(s) are
unknown: "ImageMagick"
```

**Comment by ffrancesco94** [comment]
Seems like the module was brought down. I commented those parts in the rst, will try to see if support can do anything about it.
